version: '3.3'
services:

  synthea:
    build: 
       context: frontend
    image: synthea-front-docker:latest
    environment:
      - SYNTHEA_SEED=1
      - SYNTHEA_SIZE=1000
      - FHIR_URL=http://fhir-iris:52773/synthea/fhir/r4/
    ports:
    - "5000:5000" 
    volumes:
    - type: bind
      source: ./frontend/output/fhir
      target: /synthea/output/fhir
    - type: bind
      source: ./frontend/src
      target: /app